name: Generate ASCII Artwork
on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install CowSay prograam
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover........, I am a dragon" >> dragon.txt


        - name: Sleep for 30 seconds
          run: sleep 30

        - name : check-file
          run:  ls -ltra
    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest

        steps:
        - name: sleep 10 sec
          run: sleep 10
        - name: Test_file_exists
          run: grep -i "dragon"

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        - name: Read-file
          run: cat dragon.txt

    