name: My-First-Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome-message
          run: echo  "My first Github actions job"

        - name: list-files
          run: ls -ltr

        - name: read-files
          run: cat README.md



