name: Exploring vriable and Secrets

on:
    push

env:
    CONTAINER_REGISTARY: docker.io
    DOCKER_USERNAME: siddharth1
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker build
          run: echo docker build -t ${{env.CONTAINER_REGISTARY}}/${{vars.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

        - name: Docker login
          run: echo docker login --usrname=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}